export const charactersConfig = {
    kris: {
        spriteWidth: 32,
        spriteHeight: 48,
        totalFrames: 4,
        totalAnimationLines: 4,
        scale: 2,
        speed: 0.4,
        directionLine: { down: 0, left: 1, right: 2, up: 3 },
        startX: (canvasWidth) => canvasWidth / 2,
        startY: (canvasHeight) => canvasHeight / 2,
        idleDurationRange: { min: 90, max: 260 },
        idleTriggerRange: { min: 300, max: 720 },
        directionChangeRange: { min: 80, max: 260 }
    },
    susie: {
        spriteWidth: 38,
        spriteHeight: 50,
        totalFrames: 4,
        totalAnimationLines: 4,
        scale: 2,
        speed: 0.4,
        directionLine: { down: 0, left: 1, right: 2, up: 3 },
        startX: (canvasWidth) => canvasWidth / 2,
        startY: (canvasHeight) => canvasHeight / 2,
        idleDurationRange: { min: 90, max: 260 },
        idleTriggerRange: { min: 300, max: 720 },
        directionChangeRange: { min: 80, max: 260 },
    },
    ralsei: {
        spriteWidth: 32,
        spriteHeight: 48,
        totalFrames: 4,
        totalAnimationLines: 4,
        scale: 2,
        speed: 0.4,
        directionLine: { down: 0, left: 1, right: 2, up: 3 },
        startX: (canvasWidth) => canvasWidth / 2,
        startY: (canvasHeight) => canvasHeight / 2,
        idleDurationRange: { min: 90, max: 260 },
        idleTriggerRange: { min: 300, max: 720 },
        directionChangeRange: { min: 80, max: 260 },
    },
};